# Generated by Django 6.0.1 on 2026-01-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
