# Generated by Django 6.0.1 on 2026-03-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_paper_ocr_text_paper_processed_paper_text_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='text_content',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='upload_date',
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
    ]
