# Generated by Django 6.0.1 on 2026-04-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_university_options_paper_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='analysisreport',
            name='paper',
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='paper_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='semester',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='display_name',
            field=models.CharField(default='Question Paper', max_length=255),
        ),
    ]
